import type { Metadata } from "next";
import { montserrat } from "./ui/fonts";
import "./ui/globals.css";

export const metadata: Metadata = {
  title: "Paw Pals redux",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${montserrat.className} antialiased bg-primary`}>
        <link rel="icon" href="/favicon.ico" sizes="any" />
        <header></header>
        {children}
        <footer></footer>
      </body>
    </html>
  );
}
