import type { Metadata } from "next";
import "./ui/globals.css";
import { montserrat } from "./ui/fonts";
import { StoreProvider } from "./StoreProvider";




export const metadata: Metadata = {
  title: "Paw Pals",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={montserrat.className}>
        <link rel="icon" href="/favicon.ico" sizes="any" />
        <StoreProvider>
          {children}
        </StoreProvider>
      </body>
    </html>
  );
}
